version: "3.7"

networks:
  lps-adapter-net:
    name: lps-adapter-net

services:
  lps-adapter:
    build:
      context: .
    container_name: lps-adapter    
    command:
      - "sh"
      - "-c"
      - "sh /usr/wait/wait-for-mysql.sh && npm start"
    environment:
      DB_CONFIG: integration
      KNEX_CLIENT: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testing
      REDIS_HOST: redis
      LOG_LEVEL: debug  
    ports:
      - "3000:3000"
      - "3001:3001"          
    networks:
      - lps-adapter-net
    depends_on:
      - mysql
      - redis      
    volumes:
      - ./docker:/usr/wait
      - ./test:/usr/src/app/test
      - ./migrations:/usr/src/app/migrations          
  mojaloop-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.2.3
    volumes:
      - "./spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "5000:5000"
      - "5050:5050"      
    command:
      - sh
      - -c
      - "npm start" 
  mojaloop-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v11.2.0
    ports:
      - "6060:6060"    
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh    
            

    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3000/health"]
      timeout: 20s
      retries: 10
      interval: 30s
  
  mysql:
    image: percona/percona-server
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    networks:
      - lps-adapter-net
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
#      timeout: 20s
#      retries: 10
#      start_period: 40s
#      interval: 30s

  redis:
    image: redis
    container_name: redis
    environment:
      usePassword: "false"
    ports:
      - "6379:6379"
    networks:
      - lps-adapter-net
    healthcheck:
      test: ["CMD", "redis-cli" ,"ping"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
      

