# Default values for nginx-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  replicaCount: 1
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: 0.9.0-beta.19
    pullPolicy: Always
  extraArgs:
    report-node-internal-ip-address: null
  config:
    map-hash-bucket-size: "128"
    # this doesnt work use the next one
    #client-max-body-size: "0m"
    proxy-body-size: "0m"
    proxy-read-timeout: "120"
    proxy-send-timeout: "120"
    #proxy-connect-timeout: "10"
    #enable-sticky-sessions: "true"
  stats:
      enabled: false

defaultbackend:
  replicaCount: 1
  image:
    repository: gcr.io/google_containers/defaultbackend
    tag: 1.4
    pullPolicy: Always

# TCP service key:value pairs
# Ref: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tcp
##
# tcp:
#  <nginx port>: "<namespace/service name>:<service port>"
tcp: {}

# UDP service key:value pairs
# Ref: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/udp
##
udp: {}
#  53: "kube-system/kube-dns:53"
